In [1]:
import numpy as np
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]


big_secret = np.array([first_line, second_line, third_line, second_line, first_line])
big_secret


array([[1.40000000e+01, 1.00000000e+01, 6.00000000e+00, 5.60000000e+01,
        4.00000000e+01, 2.40000000e+01, 9.80000000e+01, 7.00000000e+01,
        4.20000000e+01, 1.40000000e+02, 1.00000000e+02, 6.00000000e+01,
        1.82000000e+02, 1.30000000e+02, 7.80000000e+01, 2.24000000e+02,
        1.60000000e+02, 9.60000000e+01, 2.66000000e+02, 1.90000000e+02,
        1.14000000e+02, 3.08000000e+02, 2.20000000e+02, 1.32000000e+02,
        3.50000000e+02, 2.50000000e+02, 1.50000000e+02, 3.92000000e+02,
        2.80000000e+02, 1.68000000e+02, 4.34000000e+02, 3.10000000e+02,
        1.86000000e+02, 4.76000000e+02, 3.40000000e+02, 2.04000000e+02,
        5.18000000e+02, 3.70000000e+02, 2.22000000e+02, 5.60000000e+02,
        4.00000000e+02, 2.40000000e+02, 6.02000000e+02, 4.30000000e+02,
        2.58000000e+02, 6.44000000e+02, 4.60000000e+02, 2.76000000e+02,
        6.86000000e+02, 4.90000000e+02, 2.94000000e+02],
       [3.16227766e+01, 3.16543836e+01, 3.16859590e+01, 3.17175031e+01,
       

Чему равна сумма элементов последнего столбца массива? Ответ округлите до двух цифр после запятой:

In [17]:
new_secret_0 = big_secret[:,-1]
print(new_secret_0)
print('---------------------------------------------------------------')
round(new_secret_0.sum(),2)

[ 294.          33.1662479 2500.          33.1662479  294.       ]
---------------------------------------------------------------


3154.33

Выделите из каждой строки массива big_secret первые 5 элементов. Чему равна сумма элементов главной диагонали получившейся матрицы? Округлите ответ до двух цифр после запятой:

In [3]:
new_secret_1 = big_secret[:,:5]
print(new_secret_1)
print('---------------------------------------------------------------')
round(new_secret_1.diagonal().sum(),2)


[[14.         10.          6.         56.         40.        ]
 [31.6227766  31.65438358 31.68595904 31.71750305 31.74901573]
 [ 0.          1.          4.          9.         16.        ]
 [31.6227766  31.65438358 31.68595904 31.71750305 31.74901573]
 [14.         10.          6.         56.         40.        ]]
---------------------------------------------------------------


121.37

Выделите из каждой строки массива big_secret последние 5 элементов. Чему равно произведение элементов главной диагонали получившейся матрицы? Введите полученный результат без изменений и округлений.

In [5]:
new_secret_2 = big_secret[:,-5:]
print(new_secret_2)
print('---------------------------------------------------------------')
new_secret_2.diagonal().prod()

[[ 460.          276.          686.          490.          294.        ]
 [  33.04542328   33.07567082   33.10589071   33.13608305   33.1662479 ]
 [2116.         2209.         2304.         2401.         2500.        ]
 [  33.04542328   33.07567082   33.10589071   33.13608305   33.1662479 ]
 [ 460.          276.          686.          490.          294.        ]]
---------------------------------------------------------------


341505315559.2347

Проверим знания! Продолжим работать с массивом big_secret. Замените на 1 все элементы, у которых оба индекса нечётные, и на -1 все элементы, у которых оба индекса чётные.

In [8]:
big_secret[::2,::2] = -1 # четные индексы строк и четные индексы столбцов
big_secret[1::2,1::2] = 1 # нечетные индексы строк и нечетные индексы столбцов
big_secret

array([[-1.00000000e+00,  1.00000000e+01, -1.00000000e+00,
         5.60000000e+01, -1.00000000e+00,  2.40000000e+01,
        -1.00000000e+00,  7.00000000e+01, -1.00000000e+00,
         1.40000000e+02, -1.00000000e+00,  6.00000000e+01,
        -1.00000000e+00,  1.30000000e+02, -1.00000000e+00,
         2.24000000e+02, -1.00000000e+00,  9.60000000e+01,
        -1.00000000e+00,  1.90000000e+02, -1.00000000e+00,
         3.08000000e+02, -1.00000000e+00,  1.32000000e+02,
        -1.00000000e+00,  2.50000000e+02, -1.00000000e+00,
         3.92000000e+02, -1.00000000e+00,  1.68000000e+02,
        -1.00000000e+00,  3.10000000e+02, -1.00000000e+00,
         4.76000000e+02, -1.00000000e+00,  2.04000000e+02,
        -1.00000000e+00,  3.70000000e+02, -1.00000000e+00,
         5.60000000e+02, -1.00000000e+00,  2.40000000e+02,
        -1.00000000e+00,  4.30000000e+02, -1.00000000e+00,
         6.44000000e+02, -1.00000000e+00,  2.76000000e+02,
        -1.00000000e+00,  4.90000000e+02, -1.00000000e+0

Выделите из каждой строки обновлённого массива big_secret первые 5 элементов. Чему равна сумма элементов главной диагонали получившейся матрицы? Введите полученный ответ без изменений и округлений.

In [9]:
new_secret_3 = big_secret[:,:5]
print(new_secret_3)
print('---------------------------------------------------------------')
new_secret_3.diagonal().sum()


[[-1.         10.         -1.         56.         -1.        ]
 [31.6227766   1.         31.68595904  1.         31.74901573]
 [-1.          1.         -1.          9.         -1.        ]
 [31.6227766   1.         31.68595904  1.         31.74901573]
 [-1.         10.         -1.         56.         -1.        ]]
---------------------------------------------------------------


-1.0

Выделите из каждой строки обновлённого массива big_secret последние 5 элементов. Чему равно произведение элементов главной диагонали получившейся матрицы? Введите полученный результат без изменений и округлений.

In [10]:
new_secret_4 = big_secret[:,-5:]
print(new_secret_4)
print('---------------------------------------------------------------')
new_secret_4.diagonal().prod()

[[-1.00000000e+00  2.76000000e+02 -1.00000000e+00  4.90000000e+02
  -1.00000000e+00]
 [ 3.30454233e+01  1.00000000e+00  3.31058907e+01  1.00000000e+00
   3.31662479e+01]
 [-1.00000000e+00  2.20900000e+03 -1.00000000e+00  2.40100000e+03
  -1.00000000e+00]
 [ 3.30454233e+01  1.00000000e+00  3.31058907e+01  1.00000000e+00
   3.31662479e+01]
 [-1.00000000e+00  2.76000000e+02 -1.00000000e+00  4.90000000e+02
  -1.00000000e+00]]
---------------------------------------------------------------


-1.0

Чему равна сумма косинусов элементов первой строки массива great_secret? Ответ округлите до двух знаков после запятой.

In [4]:
import numpy as np
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T
print(great_secret)

sumcos = np.cos(great_secret)

round(np.sum(sumcos[0,:]),2)

[[ 0.          4.64158883 66.66666667]
 [ 1.          4.65700951 40.        ]
 [ 1.41421356  4.67232873 67.33333333]
 [ 1.73205081  4.68754815 40.4       ]
 [ 2.          4.70266938 68.        ]
 [ 2.23606798  4.71769398 40.8       ]
 [ 2.44948974  4.73262349 68.66666667]
 [ 2.64575131  4.7474594  41.2       ]
 [ 2.82842712  4.76220316 69.33333333]
 [ 3.          4.77685618 41.6       ]
 [ 3.16227766  4.79141986 70.        ]
 [ 3.31662479  4.80589553 42.        ]
 [ 3.46410162  4.82028453 70.66666667]
 [ 3.60555128  4.83458813 42.4       ]
 [ 3.74165739  4.84880759 71.33333333]
 [ 3.87298335  4.86294413 42.8       ]
 [ 4.          4.87699896 72.        ]
 [ 4.12310563  4.89097325 43.2       ]
 [ 4.24264069  4.90486813 72.66666667]
 [ 4.35889894  4.91868473 43.6       ]
 [ 4.47213595  4.93242415 73.33333333]
 [ 4.58257569  4.94608744 44.        ]
 [ 4.69041576  4.95967566 74.        ]
 [ 4.79583152  4.97318983 44.4       ]
 [ 4.89897949  4.98663095 74.66666667]
 [ 5.          5.        

0.16

Чему равна сумма элементов массива great_secret, значение которых больше 50?

In [5]:
np.sum(great_secret[great_secret>50])

5470.0

Переведите массив great_secret в одномерную форму. Какое значение в получившемся массиве имеет элемент с индексом 150? Скопируйте ответ из Jupyter Notebook без изменений.

In [7]:
great_secret.flatten()[150]

7.0710678118654755

Отсортируйте значения столбцов массива great_secret по возрастанию. Чему равна сумма элементов последней строки отсортированного массива? Ответ округлите до двух цифр после запятой.

In [9]:
round(np.sum(np.sort(great_secret, axis=0)[-1,:]),2)

115.12